### ISSUE TITLE
`scipy-stubs[scipy]` extra not found

### ISSUE THREAD

**Issue by lucascolley** [scipy/scipy-stubs#332]
`pip install scipy-stubs[scipy]` returns `no matches found: scipy-stubs[scipy]` for me locally. Is it just me, or is the extra not working on PyPI?

**Comment by lucascolley** [comment]
I think this is just zsh being silly, `uv add 'scipy-stubs[scipy]'` works 🙄

**Comment by jorenham** [comment]
been there, done that 🤷🏻
